name: CI-TradeStore

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Verify JAVA_HOME
      run: echo "JAVA_HOME is set to: $JAVA_HOME"

    - name: Build with Maven
      run: mvn clean install

    - name: Run Unit Tests
      run: mvn test

    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        format: 'HTML'
        project: 'TradeStore'
        path: '.'
        out: 'reports'
        args: '--noupdate --data /github/workspace/dependency-check-data'
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.jdk-path }}
